### ISSUE TITLE
Updating the version of CFITSIO on conda-forge

### ISSUE THREAD

**Issue by mohammad-akhlaghi** [conda-forge/cfitsio-feedstock#30]
The current version of CFITSIO here is 3.470 (released in May 2019: which is +2 years old), while the most recent version of CFITSIO is 4.0.0 (released in July 2021).

To help catch bugs early (especially in programs that depend on CFITSIO), it would be good to keep it up to date. Not to mention that keeping it up to date will help the direct users of CFITSIO, and the users of all the other programs that depend on CFITSIO to benefit from all the [improvements and bug fixes](https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes.txt) :wink:.

**Comment by mohammad-akhlaghi** [comment]
@sebastian-luna-valero is the Conda master that I always refer to for issues with Conda.

@sebastian-luna-valero, when you get the chance, could you help in updating CFITSIO? Its an important dependency of many software packages, including Gnuastro :wink:. Thanks in advance :+1:.

**Comment by sebastian-luna-valero** [comment]
True, we may not need them all. Due to the time between releases, and a jump to a major version, I just wanted to spot potential issues among them.
