### ISSUE TITLE
linux ppc64le travis build of 4.4.0 failed

### ISSUE THREAD

**Issue by akrherz** [conda-forge/cfitsio-feedstock#39]
### Comment:

Could a repo admin kindly look into the failed [main branch run](https://github.com/conda-forge/cfitsio-feedstock/runs/22130640308) for linux ppc64le on Travis?

Thanks

c/f conda-forge/gdal-feedstock#899

**Comment by pkgw** [comment]
This should hopefully be dealt with indirectly by #40. Travis is super unreliable at this point so we prefer to have stuff on Azure anyway. The builds are slow, but, :shrug:.

**Comment by pkgw** [comment]
Looking at anaconda.org, this issue should now be fixed.
